resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
# resolver: lts-9.21
# compiler: ghcjs-0.2.1.9009021_ghc-8.0.2
compiler-check: match-exact # Be sure you also have this line in ~/.stack/config.yaml (match-minor also works for either/both)

packages:
  - '..'
extra-deps:
  - miso-0.20.0.0
 
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
        url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
        sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
      ghcjs-0.2.1.9009021_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9009021.tar.gz
        sha1: b1740c3c99e5039ac306702894cd6e58283f4d31
        
